repos:
  - repo: https://github.com/pycqa/flake8
    rev: ''
    hooks:
      - id: flake8
        files: django_app/

  - repo: https://github.com/pycqa/isort
    rev: ''
    hooks:
      - id: isort
        files: django_app/
