# Generated by Django 4.2.4 on 2023-08-16 14:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('geo_position',
                 django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('diesel_fuel',
                 models.CharField(blank=True, default='', max_length=255)),
                ('diesel_fuel_taneco',
                 models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoadRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('start_point', models.CharField(max_length=255)),
                ('end_point', models.CharField(max_length=255)),
                ('geo_route',
                 django.contrib.gis.db.models.fields.MultiLineStringField(
                     srid=4326)),
                ('gas_stations',
                 models.ManyToManyField(blank=True, related_name='road_routes',
                                        to='road_routes.gasstation')),
            ],
        ),
    ]
